# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        /blog/:index.html

# Setup
title:            Aaron Piotrowski
tagline:          'Programming'
description:      ''
url:              http://apiotrow.github.io
baseurl:          '/'
paginate:         5

author:
  url:            https://twitter.com/mdo
  email:          markdotto@gmail.com

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
  mygithub:       https://github.com/apiotrow/

highlighter:      pygments
